In [4]:
max1demand=5    #use 1 more than actual demand
max2demand=5   #use 1 more than actual demand
max3demand=5    #use 1 more than actual demand
max4demand=5
max5demand=5
sparti=[]  #start with null
spartj=[]  #start with null
spartk=[]  #start with null
spartl=[]  #start with null
spartm=[]  #start with null
spartn=[]  #start with null
sparto=[]  #start with null
sidx=[]    #start with null
s=1        #start number for loop
for i in 1:10           #Create an index to call
    for j in 1:max1demand
        for k in 1:max2demand
            for l in 1:max3demand
                for m in 1:max4demand
                    for n in 1:max5demand
                        for o in 1:5  #5 regions
          #statei(i+1) = s
            sparti = push!(sparti,i)  #for i in ijkl add to sparti definition
            spartj = push!(spartj,j) #for j in ijkl add to spartj definition
            spartk = push!(spartk,k) #for k in ijkl add to spartk definition
            spartl = push!(spartl,l) #for l in ijkl add to spartl definition
            spartm = push!(spartm,m) #for l in ijkl add to spartl definition
            spartn = push!(spartn,n) #for l in ijkl add to spartl definition
            sparto = push!(sparto,o) #for l in ijkl add to spartl definition
            sidx= push!(sidx,s)      #create index in sidx
            s=s+1
                        end
                    end
                end
            end
        end
    end
end

idxidle= (sparti.<6) .& (spartj+spartk+spartl+spartm+spartn .>5)   #index all ijkl where idling cannot occur
idxregion1= (sparti.==6) .& (spartj.==1)      #index all ijkl where region 1 is active but there are no calls in region 1 to service
idxregion2= (sparti.==7) .& (spartk.==1)      #index all ijkl where region 2 is active but there are no calls in region 2 to service
idxregion3= (sparti.==8) .& (spartl.==1)      #index all ijkl where region 2 is active but there are no calls in region 3 to service
idxregion4= (sparti.==9) .& (spartm.==1)      #index all ijkl where region 2 is active but there are no calls in region 4 to service
idxregion5= (sparti.==10) .& (spartn.==1)     #index all ijkl where region 2 is active but there are no calls in region 5 to service        

idxDEL=idxidle .| idxregion1 .| idxregion2 .| idxregion3 .| idxregion4 .| idxregion5    #index of the previous 6 indices

deleteat!(sparti, BitArray(idxDEL)) #delete idxDEL
deleteat!(spartj, BitArray(idxDEL)) #delete idxDEL
deleteat!(spartk, BitArray(idxDEL)) #delete idxDEL
deleteat!(spartl, BitArray(idxDEL)) #delete idxDEL
deleteat!(spartm, BitArray(idxDEL)) #delete idxDEL
deleteat!(spartn, BitArray(idxDEL)) #delete idxDEL     
deleteat!(sparto, BitArray(idxDEL)) #delete idxDEL     
sidx= [1:length(sparti);]       #number of states

62525-element Vector{Int64}:
     1
     2
     3
     4
     5
     6
     7
     8
     9
    10
    11
    12
    13
     ⋮
 62514
 62515
 62516
 62517
 62518
 62519
 62520
 62521
 62522
 62523
 62524
 62525

In [260]:
μMatr= [5 4.5 4 3.5 3;     #Zone 1 to other zone rates
        4.5 5 4.5 4 3.5;   #Zone 2 to other zone rates
        4 4.5 5 4.5 4;     #Zone 3 to other zone rates
        3.5 4 4.5 5 4.5;   #Zone 4 to other zone rates
        3 3.5 4 4.5 5]     #Zone 5 to other zone rates

# s= 2048
#    Call1 = spartj[s]
#    Call2 = spartk[s]
#    Call3 = spartl[s]
#    Call4 = spartm[s]
#    Call5 = spartn[s]


# Call1-1 >=max(Call2, Call3, Call4, Call5)
# μMatr[2,3]

5×5 Matrix{Float64}:
 5.0  4.5  4.0  3.5  3.0
 4.5  5.0  4.5  4.0  3.5
 4.0  4.5  5.0  4.5  4.0
 3.5  4.0  4.5  5.0  4.5
 3.0  3.5  4.0  4.5  5.0

In [261]:
s=1 

nextZoneflag = 7
    nextCall1=1
    nextCall2=2
    nextCall3=1
    nextCall4=1
    nextCall5=1

idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2) .& (spartl.==nextCall3) .& (spartm.==nextCall4) .& (spartn.==nextCall5)
sum(idx[:,:])
        nexts= sidx[idx] 

matrix[nexts,s]= matrix[nexts,s].+λ
# matrix[s,s]= matrix[s,s]-λ
# sum(matrix)

LoadError: BoundsError: attempt to access 85×85 Matrix{Float64} at index [[774], 1]

In [3]:
#Matrix Storage
#Base5
μMatr= [5   4.5   4   3.5  3;     #Zone 1 to other zone rates
        4.5  5   4.5   4  3.5;    #Zone 2 to other zone rates
        4   4.5   5   4.5  4;     #Zone 3 to other zone rates
        3.5  4   4.5   5  4.5;    #Zone 4 to other zone rates
        3   3.5   4   4.5  5]     #Zone 5 to other zone rates
#Base4
μMatr= [4   3.5   3   2.5  2;     #Zone 1 to other zone rates
        3.5  4   3.5   3  2.5;    #Zone 2 to other zone rates
        3   3.5   4   3.5  3;     #Zone 3 to other zone rates
        2.5  3   3.5   4  3.5;    #Zone 4 to other zone rates
        2   2.5   3   3.5  4]     #Zone 5 to other zone rates

#Go100
μMatr= [105   104.5   104   103.5  103;     #Zone 1 to other zone rates
        104.5  105   104.5   104  103.5;    #Zone 2 to other zone rates
        104   104.5   105   104.5  104;     #Zone 3 to other zone rates
        103.5  104   104.5   105  104.5;    #Zone 4 to other zone rates
        103   103.5   104   104.5  105]     #Zone 5 to other zone rates
RegionFrom=5
μMatr[1,RegionFrom]

103.0

In [5]:
#Add Arrival Code
λ=.5  #Define overall Arrival Rate for every zone
λidx=zeros(length(sidx))          

μMatr= [5   4.5   4   3.5  3;     #Zone 1 to other zone rates
        4.5  5   4.5   4  3.5;    #Zone 2 to other zone rates
        4   4.5   5   4.5  4;     #Zone 3 to other zone rates
        3.5  4   4.5   5  4.5;    #Zone 4 to other zone rates
        3   3.5   4   4.5  5]     #Zone 5 to other zone rates
        
matrix= zeros(length(sidx),length(sidx))
μidx=[]


for s in 1:length(sidx)
    Zoneflag = sparti[s]
    Call1 = spartj[s]
    Call2 = spartk[s]
    Call3 = spartl[s]
    Call4 = spartm[s]
    Call5 = spartn[s]
    RegionFrom= sparto[s]
    nextZoneflag = 0
    nextCall1=0
    nextCall2=0
    nextCall3=0
    nextCall4=0
    nextCall5=0
    nexts=0
    nextRegionFrom=0
    RegionService= 0
    
    
 #   Arrival at region 1
    if Call1<max1demand
        nextCall1= Call1+1
        nextCall2= Call2
        nextCall3= Call3
        nextCall4= Call4
        nextCall5= Call5
        
        if Zoneflag <=5
            nextZoneflag = 6 #don't use double equal
            nextRegionFrom=Zoneflag
        else 
            nextZoneflag= Zoneflag
            nextRegionFrom=RegionFrom            
        end      
        idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2) .& (spartl.==nextCall3) .& (spartm.==nextCall4) .& (spartn.==nextCall5) .& (sparto.==nextRegionFrom)
        nexts= sidx[idx] 
        matrix[nexts,s].= matrix[nexts,s] .+ λ
        matrix[s,s]= matrix[s,s] - λ
        λidx[s]=1
    end

    
 #   Arrival at region 2
    if Call2<max2demand
        nextCall1= Call1
        nextCall2= Call2+1
        nextCall3= Call3
        nextCall4= Call4
        nextCall5= Call5
        if  Zoneflag <=5
            nextZoneflag = 7 #don't use double equal
            nextRegionFrom=Zoneflag
        else
            nextZoneflag= Zoneflag
            nextRegionFrom=RegionFrom
        end  

        idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2) .& (spartl.==nextCall3) .& (spartm.==nextCall4) .& (spartn.==nextCall5) .& (sparto.==nextRegionFrom)
         nexts= sidx[idx] 
         matrix[nexts,s].=matrix[nexts,s] .+ λ
         matrix[s,s]= matrix[s,s] - λ
        λidx[s]=1
    end

 #   Arrival at region 3
    if Call3<max3demand
        nextCall1= Call1
        nextCall2= Call2
        nextCall3= Call3+1
        nextCall4= Call4
        nextCall5= Call5
        
        if Zoneflag <=5 
            nextZoneflag = 8 #don't use double equal
            nextRegionFrom=Zoneflag
        else 
            nextZoneflag= Zoneflag
            nextRegionFrom=RegionFrom
        end  
        idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2) .& (spartl.==nextCall3) .& (spartm.==nextCall4) .& (spartn.==nextCall5) .& (sparto.==nextRegionFrom)
         nexts= sidx[idx] 
         matrix[nexts,s].=matrix[nexts,s].+λ
         matrix[s,s]= matrix[s,s].-λ
        λidx[s]=1
    end  
    
 #   Arrival at region 4
    if Call4<max4demand
        nextCall1= Call1
        nextCall2= Call2
        nextCall3= Call3
        nextCall4= Call4+1
        nextCall5= Call5
        
        if Zoneflag <=5 
            nextZoneflag = 9 #don't use double equal
            nextRegionFrom=Zoneflag
        else 
            nextZoneflag= Zoneflag
            nextRegionFrom=RegionFrom
        end  
        idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2) .& (spartl.==nextCall3) .& (spartm.==nextCall4) .& (spartn.==nextCall5) .& (sparto.==nextRegionFrom)
         nexts= sidx[idx] 
         matrix[nexts,s].=matrix[nexts,s].+λ
         matrix[s,s]= matrix[s,s].-λ
        λidx[s]=1
    end  
 #   Arrival at region 5
    if Call5<max5demand
        nextCall1= Call1
        nextCall2= Call2
        nextCall3= Call3
        nextCall4= Call4
        nextCall5= Call5+1
        
        if Zoneflag <=5 
            nextZoneflag = 10 #don't use double equal
            nextRegionFrom=Zoneflag
        else 
            nextZoneflag= Zoneflag
            nextRegionFrom=RegionFrom
        end  
        idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2) .& (spartl.==nextCall3) .& (spartm.==nextCall4) .& (spartn.==nextCall5) .& (sparto.==nextRegionFrom)
         nexts= sidx[idx] 
         matrix[nexts,s].=matrix[nexts,s].+λ
         matrix[s,s]= matrix[s,s].-λ
        λidx[s]=1
    end  
end   
#     Service from Region to Region
    
for s in 1:length(sidx)
    Zoneflag = sparti[s]
    Call1 = spartj[s]
    Call2 = spartk[s]
    Call3 = spartl[s]
    Call4 = spartm[s]
    Call5 = spartn[s]
    RegionFrom= sparto[s]    
    nextZoneflag = 0
    nextCall1=0
    nextCall2=0
    nextCall3=0
    nextCall4=0
    nextCall5=0
    nexts=0
    nextRegionFrom=0
    RegionService= 0
 

    if Zoneflag == 6                #Formulation for Greatest Demand Policy
        if Call1-1 >=max(Call2, Call3, Call4, Call5) && Call1-1 >1
            RegionService=μMatr[1,RegionFrom]
            nextZoneflag=6
            nextCall1=Call1-1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=1
            #μidx=push!(μidx,1)
        elseif Call1-1 >=max(Call2, Call3, Call4, Call5) && Call1-1 ==1
            RegionService=μMatr[1,RegionFrom]
            nextZoneflag=1
            nextCall1=Call1-1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5  
            nextRegionFrom=1
#             println(nextZoneflag)
        elseif max(Call2, Call3, Call4, Call5)==Call2
            RegionService=μMatr[1,RegionFrom]
            nextZoneflag=7
            nextCall1=Call1-1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=1
            #μidx=push!(μidx,1)
            
        elseif max(Call2, Call3, Call4, Call5)==Call3
            RegionService=μMatr[1,RegionFrom]
            nextZoneflag=8
            nextCall1=Call1-1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=1
            #μidx=push!(μidx,1)
                        
        elseif max(Call2, Call3, Call4, Call5)==Call4
            RegionService=μMatr[1,RegionFrom]
            nextZoneflag=9
            nextCall1=Call1-1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=1            
            #μidx=push!(μidx,1)        
        else
            RegionService=μMatr[1,RegionFrom]
            nextZoneflag= 10
            nextCall1=Call1-1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5  
            nextRegionFrom=1                
            #μidx=push!(μidx,2)
        end
 
    
    elseif Zoneflag == 7                #Formulation for Greatest Demand Policy

        if Call2-1 >=max(Call1, Call3, Call4, Call5) && Call2-1 >1
            RegionService=μMatr[2,RegionFrom]
            nextZoneflag=7
            nextCall1=Call1
            nextCall2=Call2-1
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=2            
            #μidx=push!(μidx,1)
            
        elseif Call2-1 >=max(Call1, Call3, Call4, Call5) && Call2-1 ==1
            RegionService=μMatr[2,RegionFrom]
            nextZoneflag=2
            nextCall1=Call1
            nextCall2=Call2-1
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5 
            nextRegionFrom=2                 
#             println(nextZoneflag)
        elseif max(Call1, Call3, Call4, Call5)==Call3
            RegionService=μMatr[2,RegionFrom]
            nextZoneflag=8
            nextCall1=Call1
            nextCall2=Call2-1
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=2                 
            #μidx=push!(μidx,1)
            
        elseif max(Call1, Call3, Call4, Call5)==Call1
            RegionService=μMatr[2,RegionFrom]
            nextZoneflag=6
            nextCall1=Call1
            nextCall2=Call2-1
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=2                 
            #μidx=push!(μidx,1)
                        
        elseif max(Call1, Call3, Call4, Call5)==Call4
            RegionService=μMatr[2,RegionFrom]
            nextZoneflag=9
            nextCall1=Call1
            nextCall2=Call2-1
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=2                 
            #μidx=push!(μidx,1)        
        else
            RegionService=μMatr[2,RegionFrom]
            nextZoneflag= 10
            nextCall1=Call1
            nextCall2=Call2-1
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=2                 
            #μidx=push!(μidx,2)
        end

  
    elseif Zoneflag == 8                #Formulation for Greatest Demand Policy

        if Call3-1 >=max(Call2, Call1, Call4, Call5) && Call3-1 >1
            RegionService=μMatr[3,RegionFrom]
            nextZoneflag=8
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3-1
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=3            
            #μidx=push!(μidx,1)
            
        elseif Call3-1 >=max(Call2, Call1, Call4, Call5) && Call3-1 ==1
            RegionService=μMatr[3,RegionFrom]
            nextZoneflag=3
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3-1
            nextCall4=Call4
            nextCall5=Call5 
            nextRegionFrom=3  
#             println(nextZoneflag)
        elseif max(Call2, Call1, Call4, Call5)==Call2
            RegionService=μMatr[3,RegionFrom]
            nextZoneflag=7
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3-1
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=3              
            #μidx=push!(μidx,1)
            
        elseif max(Call2, Call1, Call4, Call5)==Call4
            RegionService=μMatr[3,RegionFrom]
            nextZoneflag=9
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3-1
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=3              
            #μidx=push!(μidx,1)
                        
        elseif max(Call2, Call1, Call4, Call5)==Call1
            RegionService=μMatr[3,RegionFrom]
            nextZoneflag=6
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3-1
            nextCall4=Call4
            nextCall5=Call5
            nextRegionFrom=3              
            #μidx=push!(μidx,1)        
        else
            RegionService=μMatr[3,RegionFrom]
            nextZoneflag= 10
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3-1
            nextCall4=Call4
            nextCall5=Call5  
            nextRegionFrom=3              
            #μidx=push!(μidx,2)
        end     
                
    elseif Zoneflag == 9                #Formulation for Greatest Demand Policy

        if Call4-1 >=max(Call2, Call3, Call1, Call5) && Call4-1 > 1
            RegionService=μMatr[4,RegionFrom]
            nextZoneflag=9
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4-1
            nextCall5=Call5
            nextRegionFrom=4              
            #μidx=push!(μidx,1)
        elseif Call4-1 >=max(Call2, Call3, Call1, Call5) && Call4-1 ==1
            RegionService=μMatr[4,RegionFrom]
            nextZoneflag=4
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4-1
            nextCall5=Call5 
            nextRegionFrom=4             
#             println(nextZoneflag)
        elseif max(Call2, Call3, Call1, Call5)==Call3
            RegionService=μMatr[4,RegionFrom]
            nextZoneflag=8
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4-1
            nextCall5=Call5
            nextRegionFrom=4             
            #μidx=push!(μidx,1)
            
        elseif max(Call2, Call3, Call1, Call5)==Call5
            RegionService=μMatr[4,RegionFrom]
            nextZoneflag=10
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4-1
            nextCall5=Call5
            nextRegionFrom=4             
            #μidx=push!(μidx,1)
                        
        elseif max(Call2, Call3, Call1, Call5)==Call2
            RegionService=μMatr[4,RegionFrom]
            nextZoneflag=7
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4-1
            nextCall5=Call5
            nextRegionFrom=4             
            #μidx=push!(μidx,1)        
        else
            RegionService=μMatr[4,RegionFrom]
            nextZoneflag= 6
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4-1
            nextCall5=Call5  
            nextRegionFrom=4             
            #μidx=push!(μidx,2)
        end        
 
    elseif Zoneflag == 10                #Formulation for Greatest Demand Policy

        if Call5-1 >=max(Call2, Call3, Call4, Call1) && Call5-1 >1
            RegionService=μMatr[5,RegionFrom]
            nextZoneflag= 10
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5-1
            nextRegionFrom=5             
            #μidx=push!(μidx,1)
            
        elseif Call5-1 >=max(Call2, Call3, Call4, Call1) && Call5-1 ==1
            RegionService=μMatr[5,RegionFrom]
            nextZoneflag=5
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5-1 
            nextRegionFrom=5             
#             println(nextZoneflag)
        elseif max(Call2, Call3, Call4, Call1)==Call4
            RegionService=μMatr[5,RegionFrom]
            nextZoneflag=9
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5-1
            nextRegionFrom=5              
            #μidx=push!(μidx,1)
            
        elseif max(Call2, Call3, Call4, Call1)==Call3
            RegionService=μMatr[5,RegionFrom]
            nextZoneflag=8
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5-1
            nextRegionFrom=5              
            #μidx=push!(μidx,1)
                        
        elseif max(Call2, Call3, Call4, Call1)==Call2
            RegionService=μMatr[5,RegionFrom]
            nextZoneflag=7
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5-1
            nextRegionFrom=5              
            #μidx=push!(μidx,1)        
        else
            RegionService=μMatr[5,RegionFrom]
            nextZoneflag= 6
            nextCall1=Call1
            nextCall2=Call2
            nextCall3=Call3
            nextCall4=Call4
            nextCall5=Call5-1 
            nextRegionFrom=5              
            #μidx=push!(μidx,2)
        end                            
                    
    else
        RegionService= 0
        nextZoneflag=Zoneflag
        nextCall1=Call1
        nextCall2=Call2
        nextCall3=Call3
        nextCall4=Call4
        nextCall5=Call5
        nextRegionFrom=RegionFrom
        #μidx=push!(μidx,0)
    end 

    idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2) .& (spartl.==nextCall3) .& (spartm.==nextCall4) .& (spartn.==nextCall5) .& (sparto.==nextRegionFrom)
    nexts= sidx[idx]     
    matrix[nexts,s]=matrix[nexts,s].+RegionService
    matrix[s,s]= matrix[s,s].- RegionService     
end

matrix


62525×62525 Matrix{Float64}:
 -2.5   0.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0  -2.5   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0  -2.5   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0  -2.5   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0  -2.5   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0  -2.5  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   

In [6]:
sum(matrix[:,:])


0.0

In [16]:
print(matrix[:,100]);

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -5.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [22]:
matrix[length(sidx),:].= 1; #prep Ahat for matrix inversion

In [23]:
inverse=inv(matrix) #invert Ahat matrix
sum(inverse[:,length(sidx)]) #validate that sum of π equals 1

1.0000000000000009

In [24]:
X=inverse[:,length(sidx)] #extract π from matrix
X=round.(X,digits=10) #round to 10 digits

19225-element Vector{Float64}:
 0.0841523306
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0792026399
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0778264917
 ⋮
 5.0e-10
 2.0e-9
 2.25e-8
 6.1e-9
 2.5e-9
 4.1e-9
 3.07e-8
 1.625e-7
 5.54e-8
 3.06e-8
 5.91e-8
 1.84e-8

In [25]:
A=sparti[1:length(sidx)] 
B=spartj[1:length(sidx)]
C=spartk[1:length(sidx)]
D=spartl[1:length(sidx)]
E=spartm[1:length(sidx)]
F=spartn[1:length(sidx)]
M=hcat(sidx,A,B,C,D,E,F,X) 


19225×8 Matrix{Any}:
     1   1  1  1  1  1  1  0.0841523
     2   1  1  1  1  1  1  0.0
     3   1  1  1  1  1  1  0.0
     4   1  1  1  1  1  1  0.0
     5   1  1  1  1  1  1  0.0
     6   2  1  1  1  1  1  0.0
     7   2  1  1  1  1  1  0.0792026
     8   2  1  1  1  1  1  0.0
     9   2  1  1  1  1  1  0.0
    10   2  1  1  1  1  1  0.0
    11   3  1  1  1  1  1  0.0
    12   3  1  1  1  1  1  0.0
    13   3  1  1  1  1  1  0.0778265
     ⋮               ⋮     
 19214  10  4  4  4  4  2  5.0e-10
 19215  10  4  4  4  4  2  2.0e-9
 19216  10  4  4  4  4  3  2.25e-8
 19217  10  4  4  4  4  3  6.1e-9
 19218  10  4  4  4  4  3  2.5e-9
 19219  10  4  4  4  4  3  4.1e-9
 19220  10  4  4  4  4  3  3.07e-8
 19221  10  4  4  4  4  4  1.625e-7
 19222  10  4  4  4  4  4  5.54e-8
 19223  10  4  4  4  4  4  3.06e-8
 19224  10  4  4  4  4  4  5.91e-8
 19225  10  4  4  4  4  4  1.84e-8

In [26]:
#Percentage of time with zero calls
Midx0= (spartj .+ spartk .+ spartl.+spartm.+spartn).==5
sum(M[Midx0.==1,8])

0.4080846262

In [27]:
#Percentage of time with 1 call
Midx1= (spartj .+ spartk .+ spartl.+spartm.+spartn).==6
sum(M[Midx1.==1,8])

0.24748896399999998

In [28]:
#Percentage of time with 2 calls
Midx2= (spartj .+ spartk .+ spartl.+spartm.+spartn).==7
sum(M[Midx2.==1,8])

0.14698641859999995

In [29]:
#Percentage of time with 3 calls
Midx2= (spartj .+ spartk .+ spartl.+spartm.+spartn).==8
sum(M[Midx2.==1,8])

0.0857757921

In [30]:
#Percentage of time with 3 calls
Midx2= (spartj .+ spartk .+ spartl.+spartm.+spartn).==9
sum(M[Midx2.==1,8])

0.04950583269999998

In [31]:
#Percentage of time with max calls
MidxMax= (spartj .+ spartk.+ spartl.+spartm.+spartn).==(max1demand+max2demand+max3demand+max4demand+max5demand)
MaxInSys=sum(M[MidxMax.==1,8])

1.6721999999999998e-6

In [158]:
#Midxw1Full= ((spartj .+ spartk).<=7).&(spartj.==max1demand)
#Midxw2Full= ((spartj .+ spartk).<=7).&(spartk.==max2demand);


In [ ]:
#Define total throughput
#Throughput=((λ1+λ2)*MaxInSys+λ1*sum(M[Midxw2Full.==1,5])+λ2*sum(M[Midxw1Full.==1,5])) ###THIS IS WRONG
#Throughput=(μSame)*sum(M[μidx.==1,6])+(μDiff)*sum(M[μidx.==2,6])
Throughput=(λ)*sum(M[λidx.==1,8])*5

In [21]:
#Reward Matrix

#Dwell Reward
Rmatrix= zeros(length(sidx),length(sidx))
Reward0=10
Reward1=5
Reward2=0
Reward3=-5
for s in 1:length(sidx)
    Call1 = spartj[s]
    Call2 = spartk[s]
    Z1Reward=0
    Z2Reward=0
    if     Call1==0
    Z1Reward=Reward0
    elseif Call1==1
    Z1Reward=Reward1
    elseif Call1==2
    Z1Reward=Reward2
    else   Call1==3
    Z1Reward=Reward3
    end
  
    if     Call2==0
    Z2Reward=Reward0
    elseif Call2==1
    Z2Reward=Reward1
    elseif Call2==2
    Z2Reward=Reward2
    else   Call2==3
    Z2Reward=Reward3
    end
    DwellReward=Z1Reward+Z2Reward
    
   Rmatrix[s,s]= DwellReward
end
Rmatrix

3845×3845 Matrix{Float64}:
 10.0   0.0   0.0   0.0   0.0  0.0  0.0  …    0.0    0.0    0.0    0.0    0.0
  0.0  10.0   0.0   0.0   0.0  0.0  0.0       0.0    0.0    0.0    0.0    0.0
  0.0   0.0  10.0   0.0   0.0  0.0  0.0       0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0  10.0   0.0  0.0  0.0       0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0   0.0  10.0  0.0  0.0       0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0   0.0   0.0  5.0  0.0  …    0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0   0.0   0.0  0.0  5.0       0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0   0.0   0.0  0.0  0.0       0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0   0.0   0.0  0.0  0.0       0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0   0.0   0.0  0.0  0.0       0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0   0.0   0.0  0.0  0.0  …    0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0   0.0   0.0  0.0  0.0       0.0    0.0    0.0    0.0    0.0
  0.0   0.0   0.0   0.0   0.0  0.0  0

In [22]:
#Transition Reward

RewardUp=-5
RewardDown=5

for s in 1:length(sidx)
    Zoneflag = sparti[s]
    Call1 = spartj[s]
    Call2 = spartk[s]
    nextZoneflag = 0
    nextCall1=0
    nextCall2=0
    nexts=0
    Treward= 0
    
    
 #   Arrival at region 1
    if Call1<max1demand
        nextCall1= Call1+1
        nextCall2= Call2
        
        if Zoneflag <=3
            nextZoneflag = 3 #don't use double equal
        
        else Zoneflag == 4
            nextZoneflag = 4  #don't use double equal
        end
        idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2)
         nexts= sidx[idx]
         Rmatrix[nexts,s].=RewardUp
        
    end
      
    #Arrival at region 2
    if Call2<max2demand
        nextCall1= Call1
        nextCall2= Call2+1
        
        if Zoneflag !=3
            nextZoneflag = 4
        
        else Zoneflag == 3
                nextZoneflag = 3
        end
        idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2)
        nexts= sidx[idx] 
        Rmatrix[nexts,s].=RewardUp
    end
    
     #Service from Region to Region

    if Zoneflag == 3
        if Call1-1>=Call2 && Call1 > 2
            RegionService=μSame
            nextZoneflag=Zoneflag
            nextCall1=Call1-1
            nextCall2=Call2
            μidx=push!(μidx,1)
        
        elseif Call1-1>=Call2 && Call1==2
            RegionService=μSame
            nextZoneflag=Zoneflag-2
            nextCall1=Call1-1
            nextCall2=Call2
            μidx=push!(μidx,1)
            
        else
            RegionService=μDiff
            nextZoneflag= Zoneflag+1
            nextCall1= Call1-1
            nextCall2= Call2
            μidx=push!(μidx,2)
        end    
#         if Call1 == 2                     #Formulation for Finish Zone policy
#             if Call2 >=2
#             RegionService=μDiff
#             nextZoneflag=Zoneflag+1
#             nextCall1= Call1-1
#             nextCall2= Call2
#             else
#             RegionService=μSame
#             nextZoneflag=1
#             nextCall1= Call1-1
#             nextCall2= Call2
#             end
#             
#         else
#         RegionService=μSame
#         nextZoneflag= Zoneflag
#         nextCall1= Call1-1
#         nextCall2= Call2
#         end
        
    elseif Zoneflag == 4

        if Call2-1>=Call1 && Call2 > 2
            RegionService=μSame
            nextZoneflag=Zoneflag
            nextCall1=Call1
            nextCall2=Call2-1
            μidx=push!(μidx,1)
            
        elseif Call2-1>=Call1 && Call2==2
            RegionService=μSame
            nextZoneflag=Zoneflag-2
            nextCall1=Call1
            nextCall2=Call2-1
            μidx=push!(μidx,1)
            
                
        else
            RegionService=μDiff
            nextZoneflag= Zoneflag-1
            nextCall1= Call1
            nextCall2= Call2-1  
            μidx=push!(μidx,2)
        end
#         if Call2== 2                      #Formulation for Finish Zone Policy
#             if Call1 >=2
#             RegionService=μDiff
#             nextZoneflag=Zoneflag-1
#             nextCall1= Call1
#             nextCall2= Call2-1
#             else
#             RegionService=μSame
#             nextZoneflag=2
#             nextCall1= Call1
#             nextCall2= Call2-1     
#             end
        
#         else
#         RegionService=μSame
#         nextZoneflag= Zoneflag
#         nextCall1= Call1
#         nextCall2= Call2-1
        #         end 
    else Zoneflag <3
        
        nextZoneflag=Zoneflag
        nextCall1=Call1
        nextCall2=Call2

    end    
      #  println(RegionService)
      #  println(nextZoneflag)
      #  println(nextCall1)
      #  println(nextCall2)
        idx= (sparti.==nextZoneflag) .& (spartj.==nextCall1) .& (spartk.==nextCall2)
        #println(idx)
        #println(sidx[idx])
         nexts= sidx[idx] 
       # println(nexts)
       # println("s:", string(s))
       # println(matrix[nexts,s])
    
    if Zoneflag >=3     
    
    Rmatrix[nexts,s].=RewardDown

    end
   
        
      
end
Rmatrix

LoadError: UndefVarError: μDiff not defined

In [23]:
using LinearAlgebra
q=[]
for i in 1:length(sidx)
q= push!(q,dot(matrix[i,:],Rmatrix[i,:]))
end


In [24]:
q

3845-element Vector{Any}:
 -10.0
 -10.0
 -10.0
 -10.0
 -10.0
  -5.0
  -5.0
  -5.0
  -5.0
  -5.0
  -5.0
  -5.0
  -5.0
   ⋮
   0.0
   0.0
   0.0
   0.0
   0.0
   0.0
   0.0
   0.0
   0.0
   0.0
   0.0
 -10.0